// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import utils "github.com/leosocy/proksi/pkg/utils"

// RequestHeadersGetter is an autogenerated mock type for the RequestHeadersGetter type
type RequestHeadersGetter struct {
	mock.Mock
}

// GetRequestHeaders provides a mock function with given fields:
func (_m *RequestHeadersGetter) GetRequestHeaders() (utils.HTTPRequestHeaders, error) {
	ret := _m.Called()

	var r0 utils.HTTPRequestHeaders
	if rf, ok := ret.Get(0).(func() utils.HTTPRequestHeaders); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(utils.HTTPRequestHeaders)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequestHeadersUsingProxy provides a mock function with given fields: proxyURL
func (_m *RequestHeadersGetter) GetRequestHeadersUsingProxy(proxyURL string) (utils.HTTPRequestHeaders, error) {
	ret := _m.Called(proxyURL)

	var r0 utils.HTTPRequestHeaders
	if rf, ok := ret.Get(0).(func(string) utils.HTTPRequestHeaders); ok {
		r0 = rf(proxyURL)
	} else {
		r0 = ret.Get(0).(utils.HTTPRequestHeaders)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(proxyURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
