// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Watcher is an autogenerated mock type for the Watcher type
type Watcher struct {
	mock.Mock
}

// Receipt provides a mock function with given fields: obj
func (_m *Watcher) Receipt(obj interface{}) {
	_m.Called(obj)
}
